In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,root_mean_squared_error
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("House Price Prediction Dataset.csv")

In [3]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

In [5]:
df['Id'] = df['Id'].astype(str)

In [6]:
df.corr(numeric_only=True)

               Area  Bedrooms  Bathrooms    Floors  YearBuilt     Price
Area       1.000000  0.047523   0.021881  0.017749  -0.011609  0.001542
Bedrooms   0.047523  1.000000  -0.011990  0.010435  -0.014125 -0.003471
Bathrooms  0.021881 -0.011990   1.000000  0.029089  -0.000839 -0.015737
Floors     0.017749  0.010435   0.029089  1.000000  -0.006474  0.055890
YearBuilt -0.011609 -0.014125  -0.000839 -0.006474   1.000000  0.004845
Price      0.001542 -0.003471  -0.015737  0.055890   0.004845  1.000000

Conclusion:

From this correlation matrix we can conclude that the relationship between independent and dependent features are not strongly correlated so we can't able to use linear regression model for this dataset